name: "Validate Module"
on: [push, pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2

      - name: Run fmt
        run: terraform fmt -diff -check -no-color -recursive

      - name: Run init
        run: terraform init

      - name: Run validate
        run: terraform validate -no-color

      - uses: terraform-linters/setup-tflint@v1.1.0
        name: Setup TFLint
        with:
          tflint_version: v0.33.1

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v0.1.10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
